AMAZON BEDROCK
Fully managed
pay per use

Amazon Titan - high perf FM , image text multi model, can be cust
  Fine tuning - CHANGING WEIGHTS OF FOUNDATION MODEL, PROVIDE TRAINING DATA, SPECIFY FORMAT, STORED IN S3. nEED TO USE PROVISIONED THROUGHPUT
Instru based fine tuning is labeled examples with prompt response pairs, cheaper
  UNLABELED DATA - CONTINUE PRETRAINING , DOMAIN ADAPTATION FINE TUNING TO MAKE IT EXPERT, EXAMPLE - fEED AWS DOCUMENTATION
  SINGLE TURN MESSAGING - ESPECIALLY FOR CHATBOT
  MULTI TURN MESSAGING - CONVERSATION BASED CHATBOT WITH BIGGER CONTEXT

  RETRAINING FOUNDATION MODEL REQUIRES MORE BUDGET, INSTRUCTION BASED FINE TUNING IS LESS EPENSIVE AS COMPUTATIONS ARE LESS INTENSE AND AMOUNT OF DATA IS LESS


  TRANSFER LEARNING - CONCEPT OF REUSING A PRE TRAINED MODEL TO ADAPT IT TO NEW  RELATED TASK - USED FOR IMAGE CLASSIFICATION, NLP

  FINE TUNING USECASE - CHATBOT WITH PARTICULAR TONE, MORE UPTO DATE INFORMATION TRAINING , EXCLUSIVE DATA, TARGETED USE CASE


EVALUATION OF FOUNDATION MODEL

    IN BEDROCK WE CAN DO AUTOMATIC EVALUATION (BUILT IN TEXT SUMMARIZATION/QUESTION&ANSWER/TEXT CLASSIFICATION/ OPEN ENDED TEXT GENERATION, WE CAN BRING OUR OWN QUESTIONS
    SCORES CALCULATED AUTOMATICALLY. 
    BENCHMARK DATASETS - TO EVALUATE PERFORMANCE OF LANGUAGE MODELS
    HUMAN EVALUATION - CAN ALSO BE DONE

AUTOMATED METRICS
ROUGE - RECALL ORIENTED UNDERSTUDY FOR GISTING EVALUATION
ROUGE-N
ROUGE-L


BLEU - BILINGUAL EVALUATION UNDERSTUDY - EVALUATE QUALITY OF GENERATED TEXT, ESPECIALLY FOR TRANSLATIONS. CONSIDERS BOTH PRECISION AND PENALIZES TOO MUCH BREVITY

BERT SCORE -SEMANTIC SIMILARITY , MEANINGS SHOULD BE SAME

BUSINESS METRICS - USER FEEDBACK
ARPU

CROSS DOMAIN PERFORMANCE
CONVERSION RATE
EFFICIENCY

####

RAG - RETRIEVAL AUGMENTED GENERATION - IT IS ACTUALLY KNOWLEDGE BASE, 

DATA SOURCE WE CAN USE - S3, CONFLUENCE, SHAREPOINT,SALESFORCE, WEBPAGES

CUSOTNER SERVICE CHATBOTS
LEGAL RESEARCH ANALYSIS
HEALTHCARE QUESTIONING

      

